import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { basename, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { compile } from 'json-schema-to-typescript';
import { format } from 'prettier';

const repositoryRoot = fileURLToPath(new URL('../', import.meta.url));
const schemasRoot = resolve(repositoryRoot, 'schemas');
const outputDirectory = resolve(schemasRoot, 'generated');
const checkOnly = process.argv.includes('--check');
const prettierConfig = JSON.parse(
  readFileSync(resolve(repositoryRoot, '.prettierrc.json'), 'utf8'),
);

const schemaPaths = findSchemas(schemasRoot).filter(
  (path) => !path.includes(`${resolve(schemasRoot, 'generated')}`),
);

const generatedFiles = new Map();
for (const schemaPath of schemaPaths) {
  const schema = JSON.parse(readFileSync(schemaPath, 'utf8'));
  const generated = await compile(schema, basename(schemaPath), {
    bannerComment: '',
    additionalProperties: false,
    style: { singleQuote: true },
    unreachableDefinitions: true,
  });
  const outputName = basename(schemaPath, '.schema.json') + '.generated.ts';
  const outputPath = resolve(outputDirectory, outputName);
  const unformattedOutput = [
    '// This file is generated by scripts/generate-schemas.mjs. Do not edit manually.',
    `// Source: ${toProtocolPath(relative(repositoryRoot, schemaPath))}`,
    '',
    generated.trim(),
    '',
  ].join('\n');
  generatedFiles.set(
    outputPath,
    await format(unformattedOutput, { ...prettierConfig, filepath: outputPath }),
  );
}

if (checkOnly) {
  for (const [outputPath, output] of generatedFiles) {
    let current;
    try {
      current = readFileSync(outputPath, 'utf8');
    } catch {
      console.error(
        `Generated schema type is missing: ${toProtocolPath(relative(repositoryRoot, outputPath))}`,
      );
      process.exit(1);
    }
    if (current !== output) {
      console.error(
        `Generated schema type is stale: ${toProtocolPath(relative(repositoryRoot, outputPath))}`,
      );
      console.error('Run: npm run schemas:generate');
      process.exit(1);
    }
  }
  console.log(`Generated schema types are current (${schemaPaths.length} schemas).`);
} else {
  mkdirSync(outputDirectory, { recursive: true });
  for (const [outputPath, output] of generatedFiles) {
    writeFileSync(outputPath, output, 'utf8');
  }
  console.log(`Generated ${generatedFiles.size} TypeScript schema contracts.`);
}

function findSchemas(directory) {
  const entries = readdirSync(directory, { withFileTypes: true });
  const paths = [];
  for (const entry of entries) {
    const path = resolve(directory, entry.name);
    if (entry.isDirectory()) {
      paths.push(...findSchemas(path));
    } else if (entry.isFile() && entry.name.endsWith('.schema.json')) {
      paths.push(path);
    }
  }
  return paths.sort((left, right) => left.localeCompare(right, 'en'));
}

function toProtocolPath(path) {
  return path.replaceAll('\\', '/');
}
